### ISSUE TITLE
Update the docker-ce, git and docker-compose

### ISSUE THREAD

**Issue by ZPascal** [cloudfoundry-community/containers-boshrelease#14]
Hi @jhunt,

I have [checked](https://github.com/jhunt/containers-boshrelease/blob/master/packages/docker/packaging) and the appropriate versions of Git, Docker and compose and I would recommend updating the outdated versions. We have already faced a warning of our security checking tool. 

Should I prepare a PR with the new versions or do you want to change the versions as you did it [last time](https://github.com/jhunt/containers-boshrelease/issues/4)?

**Comment by jhunt** [comment]
IIRC, it comes down to bucket access.  If you want to do the PR with a local release, and include the URLs for the blobs, I can amend the PR and merge the final product.
