### ISSUE TITLE
thoughts on leveraging self-links with this release?

### ISSUE THREAD

**Issue by aegershman** [cloudfoundry-community/containers-boshrelease#3]
(forgive me, I haven't done much research into the viability of this, I'm part _asking_ and part _getting thoughts out_)

any thoughts on a way to modify the `docker` job to provide [self-referential `links`](https://bosh.io/docs/links/#self) so docker image on separate `docker/*` deployment instances could pass address references to one another as peers?

... I guess this wouldn't really work since `links` only work in rendered template jobs, not as accessible values in job properties (e.g. the `recipe:` key), but I'll postulate this regardless

## background

I'm curious about using a BOSH-orchestrated deployment of [`docker-splunk`](https://github.com/splunk/docker-splunk) Heavy Forwarders for `syslog` and http endpoint collection. I'm running a dedicated k8s cluster for it right now, but I'm interested in moving it to being BOSH-managed to keep it in line with my standard BOSH deployment suite.

If the `splunk` images can be passed the addresses of their peers, they can work in a cluster. I _might_ be able to finagle them talking to each other using `links` similar to how [the `minio-boshrelease` has all the instances link to one another](https://github.com/minio/minio-boshrelease/blob/master/jobs/minio-server/templates/ctl.erb#L49)

thoughts welcome, i'll probably experiment with this over the next few weeks or months just to see what options there are. Thanks for any time. We can close this out whenever 👍

**Comment by jhunt** [comment]
I'm curious to see where your experiments lead.  Cross-node communication was not an original design goal of this BOSH release, but it's a desirable one nonetheless.

I'm curious about your aversion to using a dedicated Kubernetes cluster.  I've been mostly going the opposite direction, where I want BOSH to _only_ deploy Kubernetes and then migrate more of my BOSH-bound stuff _to_ Kubernetes.

**Comment by aegershman** [comment]
AFAICT, there's no way to do cross-node comms using `bosh` linking semantics in any way (since they're only available within job template configs via `erb`). And there's no `docker`-related cross comms as we know, e.g. something akin to `swarm` with `networks` (or, you know... k8s)

There's just an enormous amount of flux in the k8s ecosystem (see: entire cloud industry) at the moment, which isn't a _bad_ thing, necessarily. But I've already got a very strong `bosh` toolchain & ecosystem which serves as the backbone for our envs in multiple IaaSes, regions, etc. Prometheus-boshrelease is easy-peezy, the upgrade & versioning toolchain is already in place; it's easy to tie in `syslog_release` for consuming app and deployment logs; I can wire up the CF `routing_release` right into this release to get both HTTPS and TCP routing without having to worry about tracking upgrade paths of k8s `certmanager`, `external-dns`, `nginx-ingress`, migrating from `helm2` to `helm3`, migrating volumes between storage providers if necessary, etc., etc.

It's not that I don't like k8s by any means-- there are brilliant ideas and opportunities I'm excited by-- but being entirely pragmatic, there's so much good plumbing already wired together in my bosh ecosystem which all fits together elegantly and quickly than spending the work time to re-invent (rather, "re-consume"? "re-discover"?) the wheel; and I mean that "re-invent" phrase in the least-condescending way to k8s as possible. Using bosh to orchestrate docker to consume (certain) docker containers is a pretty dang good in-between for (certain) use-cases.

ya know what I mean? hope that wasn't too rambly

**Comment by jhunt** [comment]
I had some old code lying around in a working copy that I never properly branchified.  One of these days I'll get better at git.

I pushed the WIP commit to the `linky-linky` branch, here: https://github.com/jhunt/containers-boshrelease/tree/linky-linky

The idea was that BOSH operators could build more complicated stuff by using the `containers` link, cross-job to at least facilitate discovery of IP address (or BOSH DNS names).  I haven't played with it on anything more advanced than a single VM type linking to its other instance group instances (see `manifests/redis-cluster`)

I'd love to use that branch as a staging area for this type of work, if you're still interested in the functionality @aegershman

**Comment by aegershman** [comment]
I am, I can't get to it anytime obviously soon unfortunately, but can we leave this open for a few weeks and if I get some time I'll try to see what can be done with this? This could be really valuable.

I like this idea, if I'm understanding correctly the only thing is getting the content of that file which contains the values of the `links` on disk fed into params which are expecting those values "up front" and spoonfed into it rather than reading them from a file on disk... which I guess is a big "only thing", tbh.

There might be a way to interpolate those values into the rendering of a `docker-compose.yml` by introducing another small layer of interpolation, e.g. when / after `docker-compose` is rendered, another step could replace any (user-supplied) identifiers such as `LINKY_LINKS` with a corresponding value which comes from the 'real' `<% link("...").ips =>` erb interpolation... you know what I mean?

I have some ideas; they might turn out to be total trash, but it might work. Let me goof on this just a bit a little later?

**Comment by jhunt** [comment]
Take all the time you need.  I'd be curious what your concrete use case is; maybe I could find some time to hack on that solution for a bit, as well.

Keep me posted.

**Comment by aegershman** [comment]
**TL,DR;** I don't think there's a rock-solid concrete use-case

So, my original thought on this was to introduce a hodge-podge interpolation step to the `docker-compose` template would be. Basically in the docker-compose.yml, in fields where you'd want to pass the addresses of all the other nodes in the deployment, you'd reference it as something like `${LINK_INSTANCES_ADDRESSES}`.

And then right before the `docker-compose.yml` is actually _used_, a shell script would interpolate the `docker-compose` with those common values which you have access to through bosh erb. For example, `${LINK_INSTANCES_ADDRESSES}` would be...

```sh
# I'm sure there's a more succinct way to do this
LINK_INSTANCES_ADDRESSES=<%= link("containers").instances.map { |i| "#{i.address}"}.join(",") %>
```

and then if your docker-compose.yml had `${LINK_INSTANCES_ADDRESSES}` referenced in it, it'd be replaced with the value of `q-xyz.q123.bosh,q-abc.q123.bosh,q-zzz.q123.bosh`, and passed to the docker container as such. You definitely wouldn't have access to bosh erb's full range of templating and values, but perhaps some common attributes.

That's the _idea_, but to be honest I'm not jazzed about it or if it'd legitimately offer value that'd be used. My use case of having the splunk container image orchestrated together in a cluster is likely an edge-case, and honestly, it works _fine_ as a cluster of standalone images operating independently. I think at a certain point of complexity and reliance, it's better to commit to operating a dedicated boshrelease for `<whatever thing>`-- or, like, working out an actual k8s strategy alongside bosh.

I'll go ahead and close this out; thanks for your time && for letting me talk out the idea and thought process 👍we can definitely reopen it to reconsider or talk it through more
