### ISSUE TITLE
Bumping packages to latest docker-ce and git

### ISSUE THREAD

**Issue by aegershman** [cloudfoundry-community/containers-boshrelease#4]
In order to leverage the latest stable versions of the [software packages this boshrelease uses](https://github.com/cloudfoundry-community/containers-boshrelease/blob/master/packages/docker/spec), consider bumping to the [latest stable version of `docker` at 19.03.5](https://github.com/docker/docker-ce/releases/tag/v19.03.5), and [git 2.25.0](https://github.com/git/git/releases/tag/v2.25.0)

Admittedly, these aren't the most critical things in the world, just putting them out there. If there's a way to coerce bumping the `ci` to consume these newer packages / updating the job templates, please do let me know and I can submit a PR, so apologies if this comes off as lazy for not actually doing the work myself. Thanks 👍

**Comment by jhunt** [comment]
I can knock this out.

**Comment by jhunt** [comment]
```
docker/6865e566-848f-4688-85bd-0e2dc40a0689:~$ /var/vcap/packages/docker/bin/git --version
git version 2.25.0
docker/6865e566-848f-4688-85bd-0e2dc40a0689:~$ /var/vcap/packages/docker/bin/docker --version
Docker version 19.03.5, build 633a0ea838
```

I'll get a release cut soon-ish.

**Comment by jhunt** [comment]
Done in the 1.1.0 release: https://github.com/cloudfoundry-community/containers-boshrelease/releases/tag/v1.1.0

🍻

**Comment by aegershman** [comment]
👍🙏
