### ISSUE TITLE
No longer seeing stdout from docker images via compose as of 1.1.0

### ISSUE THREAD

**Issue by aegershman** [cloudfoundry-community/containers-boshrelease#6]
It appears I'm no longer seeing logs from `stdout/stderr` logging from docker images running processes; I'm _thinking_ it's akin to this configuration log line in the `docker-compose` job that was previous in 1.0.0, which was:

```sh
...
exec >>$LOG_DIR/compose.log 2>&1
```

That's a pure shot in the dark though, I'm sorry, I haven't looked too deep into it yet. Just wanted to log this first. With some time I'll do some further investigation. Thanks a lot for your time & attention 👌

**Comment by jhunt** [comment]
Yeah, the problem is that compose is gone (as a job) and the post-start script does a `compose -d`; if you want logs you have to hit the docker daemon itself.
